apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-deployment
        image: samsanimahesh/flask-host-image
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-deployment-svc
  labels:
    app: flask-app
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30080
  selector:
    app: flask-app

