apiVersion: v1
kind: Service
metadata:
  name: flask-one
  labels:
    app: flask-app
    role: load-balancer
spec:
  selector:
    app: flask-app
    role: load-balancer
  type: NodePort
  ports:
    - name: flask-one
      port: 5000
      targetPort: 5000
